
# layout
## menu
menu:
- page: home
  url: /
  icon: fa-home
- page: archives
  url: /archives
  icon: fa-archive
#- page: about
#  url: /about
#  icon: fa-user
- page: rss
  url: /atom.xml
  icon: fa-rss
## favicon
favicon: /favicon.ico
## rss
rss: /atom.xml
## widgets
widgets:
- notification
- category
- archive
- popular
- tagcloud
- friends
## widgets settings
### notification config --support html/text
notification: |-

            <p>Hexo主题ylion v0.0.1版本即将上线，敬请期待~！
            主题作者：<a href="https://github.com/GeekaholicLin"
            title="fork me" target="_blank">Geekaholic</a></p>

### categories-list config
cate_config:
 show_count: true
### archives-list config
arch_config:
 type: 'monthly'
 show_count: true
 order: -1

### tagcloud config
tagcloud_config:
 min_font: 0.14
 max_font: 0.2
 unit: rem
 amount: 100
 color: true
 orderby: 'count'
 start_color: '#6699cc'
 end_color: '#0A407C'
### friends' links settings
links:
- 主题作者: http://geekaholiclin.github.io
- walkerlala: http://walkerlala.github.com/
- 璀璨星空: http://jerry011235.github.io/
# content
## show top posts or not
stick: true
## social config
social:
- url: https://freecodecamp.cn/geekaholiclin
  title: freecodecamp
  icon: fa-free-code-camp
- url: https://github.com/GeekaholicLin
  title: github
  icon: fa-github
- url: https://leetcode.com/geekaholic/
  title: leetcode
  icon: fa-code
- url: https://www.zhihu.com/people/geekaholic/activities
  title: 知乎
  icon: fa-graduation-cap
- url: mailto:geekaholiclin@gmail.com
  title: mail to me
  icon: fa-envelope-o

## custom content config
### append copyright when copy the text
appendCopyright:
  enable: true
  triggerCopyLength: 200
  appendText: '商业转载请联系作者获得授权,非商业转载请注明出处 © GeekaholicLin'
### uncategory posts meta text
noCategoryText: 'null'
### outdated browser warning
outdated_browser_text: '您使用的浏览器版本过低，为了您更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'
### outdated post warning
warning:
  days: 300 #default is 300 days
  text: '本文于%d天之前发表，文中内容可能已经过时。如有疑问，请在评论区留言。'

### index article excerpt
defaultImgs:
  - http://olb32qrq7.bkt.clouddn.com/blog-bg3.jpg
  - http://olb32qrq7.bkt.clouddn.com/blog-bg4.png
  - http://olb32qrq7.bkt.clouddn.com/blog-bg5.jpg
  - http://olb32qrq7.bkt.clouddn.com/blog-bg6.jpg
#  - /img/default-1.jpg

excerptLength: 400
### article meta
whichCategory: 0
### post footer
high_song: 'high起来 &#128541;'
author_img: http://olb32qrq7.bkt.clouddn.com/author.jpg
author_profile_page: /about.html # default is the blog home
donate:
  text: '打赏资瓷 &#128536;'
  img:
  - url: http://olb32qrq7.bkt.clouddn.com/alipay.jpg
    alt: '支付宝付款'
  - url: http://olb32qrq7.bkt.clouddn.com/wechat.png
    alt: '微信付款'
# support html&text like notification's support in this theme,
# but please don't use <li> tag
cc: |-

        <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank">
        知识共享署名-非商业性使用-禁止演绎 3.0 未本地化版本许可协议（CC BY-NC-ND 3.0）
        </a>

# third party service
## busuanzi
visits_count:
  enable:  true
  icon: fa-bar-chart
  text: '欢迎第%d位小伙伴~'
  count_method: 'uv'

## leancloud
leancloud:
  enable: true
  className: "BlogCounter"
  app_id: RI5uv752sD0nGTyUSUC6odJE-gzGzoHsz
  app_key: yuke8QmutaxI5YvyD2NIE57u
  region:
  limits: 10 # popular posts will be disable when 0
## comments
### disqus
#disqus_shortname: geekaholiclin
### duoshuo
duoshuo_shortname: garcin
## analytics
baidu_anaylytics: 1fdc784829bc9fa0c0bbee0c680ffe2a
google_anaylytics: UA-91854900-3
## sitemap
google_vertification: osGzKb_y9J6vt8d0mGYPDH81ljatwPdSVCFwxMCJSaE
baidu_vertification: Yn6v4uAWVY
# cdn or local files
## style cdn

fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## script cdn

leancloud_src: http://cdn1.lncld.net/static/js/2.1.0/av-min.js
busuanzi_src: //dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js

# theme and site self settings
since: 2015
robot: 'all' #default is all
version: v0.0.1
